logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        beans:
          factory: info

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: auth-data
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_SERVER}
      client:
        registration:
          demo-backend:
            provider: auth-server
            client-id: spring-demo
            client-secret: "<OAUTH Server Client Secret>"
            authorization-grant-type: "client_credentials"
            scope: "openid"
        provider:
          auth-server:
            issuer-uri: ${OAUTH_SERVER}
  datasource:
    url: jdbc:${USERS_DB_FLAVOR}://${USERS_DB_SERVER}/${USERS_DB}
    username: ${USERS_USERNAME}
    password: ${USERS_PASSWORD}
    driver-class-name: ${USERS_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: false

demoData: # Demo application configuration
  scenarios:
    dir: "file:${DEMO_DATA}/scenarios"
  auth:
    admin_server: ${OAUTH_ADMIN_SERVER}
    client_name: ${OAUTH_CLIENT}


springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/docs-ui"
    disable-swagger-default-url: true
